console.log("Hello World!")
console.warn("Hello World!")
console.error("Hello World!")
//document.write("Hello World!")
//document.write("<h1>Hello World!</h1>")
//document.write("<h2>Hello World!</h2>")